export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const INIT_LOCATION = 'INIT_LOCATION';
export const INIT_DATE = 'INIT_DATE';

export const CHECK_USER_REQUEST = 'CHECK_USER_REQUEST';
export const CHECK_USER_SUCCESS = 'CHECK_USER_SUCCESS';
export const CHECK_USER_FAIL = 'CHECK_USER_FAIL';

export const GET_ME_REQUEST= 'GET_ME_REQUEST';
export const GET_ME_SUCCESS= 'GET_ME_SUCCESS';
export const GET_ME_RESET= 'GET_ME_RESET';

export const ERROR_RESET= 'ERROR_RESET';